### ISSUE TITLE
Escolha dos Dados

### ISSUE THREAD

**Issue by lividullius** [lividullius/presidentes#1]

**Comment by lividullius** [comment]
Tabela de Dados: Presidentes do Brasil
https://pt.wikipedia.org/wiki/Lista_de_presidentes_do_Brasil

**Comment by lividullius** [comment]
https://pt.wikipedia.org/wiki/Lista_de_presidentes_do_Brasil

**Comment by Danckwardtt** [comment]
Tabela de dados 2: Presidentes dos Estados Unidos 
https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States
