### ISSUE TITLE
Implementação da Classe

### ISSUE THREAD

**Issue by lividullius** [lividullius/presidentes#3]
A classe construtora Presidentes (incluindo presidentes do Brasil e dos Estados Unidos) representa dados sobre cada presidente da história. Cada presidente é representado por sete campos de dados.

**Comment by lividullius** [comment]
Classe App Presidentes do Brasil com os atributos numero, nome, nomeVice, partido, anoinicio, anofim, posse de cada Presidente Brasileiro.

**Comment by lividullius** [comment]
Classe App Presidentes dos EUA com os atributos numero, nome, nomeVice, partido, anoinicio, anofim, posse de cada Presidente Americano.

**Comment by lividullius** [comment]
![Capturar](https://github.com/user-attachments/assets/d4aeff18-d946-4f20-9019-93f05dd1f9e0)

**Comment by lividullius** [comment]
![Capturar 4](https://github.com/user-attachments/assets/7e20b185-52be-47aa-8519-860991385ba6)

**Comment by lividullius** [comment]
@startuml

class Presidentes {
    -numero :int
    -nome : String
    -nomeVice : String
    -partido: String
    -anoinicio : int
    -anofim : int
    -posse: String
    +Presidentes(int numero, String nome, String nomeVice, String partido, int anoinicio, int anofim, String posse)
    +getNumero() : int
    +getNome():String
    +getNomeVice() : String
    +getPartido() : String
    +getAnoInicio() : int
    +getAnoFim() : int
    +getPosse() : String
    +setNumero(int novoNumero) : void
    +setNome(String novoNome) : void
    +setNomeVice(String novoNomeVice) : void
    +setAnoInicio(int novoAnoInico) : void
    +setAnoFim(int novoAnoFim) : void
    +setPosse(String novaPosse) : void
    +toString() : String
}

class PresidentesBR {
    +{static} main(String[] args) : void
}
class PresidentesEua{
    +{static} main(String[] args) : void
}

PresidentesBR ...> Presidentes : uses
PresidentesEua...> Presidentes : uses
@enduml

**Comment by Danckwardtt** [comment]
A implementação da classe Presidentes foi realizada em período de aula sem muito esforço

**Comment by Danckwardtt** [comment]
Quanto ao  toString tivemos dificuldade em implementar este método de uma forma visualmente mais organizada. Foram realizadas pesquisas sobre como dispor tal dados como aos de uma tabela
@see https://youtu.be/Kfc6p41-Iq8?si=ruzEbe7-pDBPQ_Vw
Após algumas tentativas falhas resolvemos permanecer com o método anteriormente criado
