### ISSUE TITLE
Criação de Arquivo de Dados

### ISSUE THREAD

**Issue by lividullius** [lividullius/presidentes#4]
Acrescentar presidentes nos arquivos.

**Comment by Danckwardtt** [comment]
A realização do arquivo de dados foi uma das ultimas coisas implementadas pois demoramos para compreender o que deveria conter nela. Inicialmente foi pesquisado sobre o tipo de arquivo .csv para depois realizar a troca de artigo.doc para artigo.csv utilizando um conversor

**Comment by Danckwardtt** [comment]
Foi realizado implementado pelo Raul, os arguivos de dados de ambas as classes PresidentesBR e PresidentesEua
