### ISSUE TITLE
Diagrama de Classe UML

### ISSUE THREAD

**Issue by lividullius** [lividullius/presidentes#7]
O diagrama de classe UML foi iniciado utilizando o PlantUml
@see https://www.plantuml.com/

**Comment by Danckwardtt** [comment]
Diagrama iniciado utilizando o PlantUml
@see https://www.plantuml.com/

**Comment by Danckwardtt** [comment]
![Captura de tela 2024-09-05 104235](https://github.com/user-attachments/assets/10fefb78-748a-4cdd-b0bb-fe06e06ab8c6)

**Comment by Danckwardtt** [comment]
Atualização do Raul
![Captura de tela 2024-09-05 104514](https://github.com/user-attachments/assets/1d2681ea-b338-4878-a779-5870113b7942)

**Comment by lividullius** [comment]
(https://www.plantuml.com/plantuml/png/bPB1IiGm48RlVOeSTr7x03t8AYXuaQBWHJo4DfQ19hDqqhsKlhlJJ4dJZHxiRVxvPlv_Ga_azU17snTDhubKFHY2rZXlI4s5uk_EZTOCg2fmVXNG6bMfTp-0wpRf0vfh-SoxeSMzg1s2WmQGOTafuZVOL3aZaTbDtYJX3imfINQxCce9aHIIA0gIXUbbCcQGKjmZ6goFujaP_nfi3iSjdSZiS3XMCfEeuXlmgruj4NvhFJXy2O4o6-uyWytacZFc9XJJXlV12qgvS1U4Db8Xl4mAndKEoIqPo5eEnmkYzQhavd9IvAJCABbmizP1s6CUfPy-n5pa__BZcvfaOYAlFJIpiXhSkltpI-cXexXwpXSyZVfV2ugzULcMz-aw1aSoLEmT_g9EnhMZxNy0)

**Comment by Danckwardtt** [comment]
Consulta com O Professor Duncan Ruiz para fiscalização diagrama de Classes .
