### ISSUE TITLE
Relatório de Fontes Consultadas

### ISSUE THREAD

**Issue by lividullius** [lividullius/presidentes#8]

**Comment by lividullius** [comment]
Segunda fonte consultada: lista dos presidentes dos Estados Unidos na wikipedia. https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States

**Comment by Danckwardtt** [comment]
Common commands on PlantUml
utilizado a própria plataforma para o entendimento para realização do diagrama de classe  Uml
https://plantuml.com/commons

**Comment by lividullius** [comment]
Quarta fonte consultada: ChatGPT para verificação do código e se não tinha nenhum erro.

**Comment by RaulVJ123** [comment]
Através da realização desse trabalho, a minha pessoa apresenta a capacidade concluir que, através da confecção deste ofício, ela conseguiu expandir seus conhecimentos envolvendo o uso de ArrayList, bem como a descoberta de possibilidade de utilizar esse recurso associado a um objeto criado pelo próprio programador. Sobre as eventuais dificuldades enfrentadas pelo autor desse comentário, elas se resumem à dificuldade inicial na classe PresidentesBr de salvar diferentes conteúdos em posições variadas do array, desafio esse que eu acabei superando por meio da aplicação de uma variável pertencente ao tipo do objeto criado seguido do método add() para expandir a lista várias vezes, sendo que, cada vez que eu aplicava essa variável, eu alterava o seu conteúdo de acordo com os dados que a minha pessoa gostaria de inserir antes de expandir o array usando o método add(). À respeito do meu papel neste trabalho, ele se resumiu à criação das classes Presidente, na qual foi determinada as informações que os objetos de tipo, cujo nome é o mesmo da classe, iriam armazenar, além dos diversos métodos getter e setters, que, em tese, permitiriam a obtenção e alteração de determinada informação contida no objeto, embora, na realidade, esses métodos não tenham sidos utilizados na aplicação, e do método toString, para orientar o modo pelo qual as informações do objeto serão impressas, PresidentesBr e PresidentesEua, sendo que essas duas classes usam a primeira classe mencionada para gerar e imprimir as informações referentes aos presidentes desses dois países, operação essa feita por meio do uso do "for", que verifica cada posição do Array, do método get() para "pegar" os conteúdos de determinada posição no Array e do "System.out.println()"para imprimir o conteúdo do objeto localizado em cada posição do Array, à correções na representação da versão UML do programa construído, baseadas nas representações UML apresentadas em aula, e à construção dos Arquivos de Dados referentes às informações inseridas nas classes PresidenteBr e PresidenteEua. E, por fim, sobre os recursos utilizados pela minha pessoa visando a realização da atividade proposta, eles consistiram nas páginas da Wikipédia sobre os presidentes dos dois países, a seção 7.16 do livro Java: Como Programar, de Harvey Deitel e Paul Deitel, e do Plant UML para aplicar correções na representação UML do programa criado.
Fontes utilizadas no trabalho:
Lista de Presidentes do Brasil. Disponível em: <https://pt.wikipedia.org/wiki/Lista_de_presidentes_do_Brasil>. Acesso em: 2 de Set. 2024.
List of presidents of the United States. Disponível em: <https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States>. Acesso em: 3 de Set. 2024.
Plant Uml Server. Disponível em: <https://plantuml.com/commons>. Acesso em: 5 de Set. 2024.
ChatGPT. Disponível em: <https://chatgpt.com/>. Acesso em: 5 de Set.
Deitel, Harvey; Deitel, Paul. Java: Como Programar. 10. ed. São Paulo: Pearson Education do Brasil, 2017. p. 226-227.
